=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd_patricia.v1/01-AtivacaooDACC/ListaAtivacaoDACC_In.dtd
<!ELEMENT SiebelMessage (ListaAtivacaoDACC?) >
<!ATTLIST SiebelMessage MessageId		CDATA #IMPLIED>
<!ATTLIST SiebelMessage MessageType		CDATA #IMPLIED>
<!ATTLIST SiebelMessage IntObjectName	CDATA #IMPLIED>
<!ELEMENT ListaAtivacaoDACC (Dados+) >
<!ELEMENT Dados (ListaDocumentos?, ListaFaturas?)>
<!ATTLIST Dados OrigemRequisicao CDATA #IMPLIED >
<!ELEMENT ListaDocumentos (Documento*) >
<!ELEMENT Documento (TipoDocumento?, NumeroDocumento?)>
<!ELEMENT ListaFaturas (ContaFatura*) >
<!ELEMENT ContaFatura (NumeroConta?, TipoCobranca?, CodigoBanco?, CodigoAgencia?, ContaCorrente?, PDV?, LoginVendedor?, NomeBanco?, NumeroCartaoCredito?)>
<!ELEMENT TipoDocumento 		(#PCDATA) >
<!ELEMENT NumeroDocumento 		(#PCDATA) >
<!ELEMENT NumeroConta 			(#PCDATA) >
<!ELEMENT TipoCobranca 			(#PCDATA) >
<!ELEMENT CodigoBanco 			(#PCDATA) >
<!ELEMENT CodigoAgencia 		(#PCDATA) >
<!ELEMENT ContaCorrente 		(#PCDATA) >
<!ELEMENT PDV 					(#PCDATA) >
<!ELEMENT LoginVendedor			(#PCDATA) >
<!ELEMENT NomeBanco				(#PCDATA) >
<!ELEMENT NumeroCartaoCredito	(#PCDATA) >

=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd_patricia.v1/01-AtivacaooDACC/ListaAtivacaoDACC_In.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SiebelMessage SYSTEM "ListaAtivacaoDACC_In.dtd" >
<SiebelMessage IntObjectName="" MessageId="" MessageType="">
  <ListaAtivacaoDACC>
    <Dados OrigemRequisicao="">
      <ListaDocumentos>
        <Documento>
          <TipoDocumento>TipoDocumento</TipoDocumento>
          <NumeroDocumento>NumeroDocumento</NumeroDocumento>
        </Documento>
      </ListaDocumentos>
      <ListaFaturas>
        <ContaFatura>
          <NumeroConta>NumeroConta</NumeroConta>
          <TipoCobranca>TipoCobranca</TipoCobranca>
          <CodigoBanco>CodigoBanco</CodigoBanco>
          <CodigoAgencia>CodigoAgencia</CodigoAgencia>
          <ContaCorrente>ContaCorrente</ContaCorrente>
          <PDV>PDV</PDV>
          <LoginVendedor>LoginVendedor</LoginVendedor>
          <NomeBanco>NomeBanco</NomeBanco>
          <NumeroCartaoCredito>NumeroCartaoCredito</NumeroCartaoCredito>
        </ContaFatura>
      </ListaFaturas>
    </Dados>
  </ListaAtivacaoDACC>
</SiebelMessage>
