=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd_patricia.v1/LIstaRetorno.dtd
<!-- Copyright (C) 1994, Siebel Systems, L.P., All rights reserved. -->
<!-- Siebel DTD Generation -->
<!ELEMENT SiebelMessage (ListaRetorno?) >
<!ATTLIST SiebelMessage MessageId CDATA #IMPLIED>
<!ATTLIST SiebelMessage MessageType CDATA #IMPLIED>
<!ATTLIST SiebelMessage IntObjectName CDATA #IMPLIED>
<!ELEMENT ListaRetorno (Retorno+)>
<!ELEMENT Retorno (Codigo?,Mensagem?,ListaMeioDeAcesso?)>
<!ELEMENT Codigo (#PCDATA) >
<!ELEMENT Mensagem (#PCDATA) >
<!ELEMENT ListaMeioDeAcesso (MeioDeAcesso*) >
<!ELEMENT MeioDeAcesso (MSISDN?)>
<!ELEMENT MSISDN (#PCDATA) >

=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd_patricia.v1/LIstaRetorno1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SiebelMessage SYSTEM "LIstaRetorno.dtd" >
<SiebelMessage IntObjectName="" MessageId="" MessageType="">
  <ListaRetorno>
    <Retorno>
      <Codigo>Codigo</Codigo>
      <Mensagem>Mensagem</Mensagem>
      <ListaMeioDeAcesso>
        <MeioDeAcesso>
          <MSISDN>MSISDN</MSISDN>
        </MeioDeAcesso>
        <MeioDeAcesso>
          <MSISDN>MSISDN</MSISDN>
        </MeioDeAcesso>
        <MeioDeAcesso>
          <MSISDN>MSISDN</MSISDN>
        </MeioDeAcesso>
        <MeioDeAcesso>
          <MSISDN>MSISDN</MSISDN>
        </MeioDeAcesso>
      </ListaMeioDeAcesso>
    </Retorno>
  </ListaRetorno>
</SiebelMessage>
