=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd/ListaCriarOrdemServico.dtd
<!-- Copyright (C) 1994, Siebel Systems, L.P., All rights reserved. -->
<!-- Siebel DTD Generation -->
<!ELEMENT SiebelMessage (ListaCriarOrdemServico?) >
<!ATTLIST SiebelMessage MessageId CDATA #IMPLIED>
<!ATTLIST SiebelMessage MessageType CDATA #IMPLIED>
<!ATTLIST SiebelMessage IntObjectName CDATA #IMPLIED>
<!ELEMENT ListaCriarOrdemServico (Dados+)>
<!ELEMENT Dados (ListaOrdens?)>
<!ATTLIST Dados OrigemRequisicao CDATA #IMPLIED >
<!ELEMENT ListaOrdens (Ordem*) >
<!ELEMENT Ordem (NumeroContaFatura?,NomePlano?,NomeCampanha?,NomeOferta?,PDV?,ListaInstancias?,ListaConvergentes?)>
<!ELEMENT NumeroContaFatura (#PCDATA) >
<!ELEMENT NomePlano (#PCDATA) >
<!ELEMENT NomeCampanha (#PCDATA) >
<!ELEMENT NomeOferta (#PCDATA) >
<!ELEMENT PDV (#PCDATA) >
<!ELEMENT ListaInstancias (Instancias*) >
<!ELEMENT Instancias (AcaoInstancia?,DDD?,OiChip?,MSISDN?,IMEI?,OpcaoOiDados?,Relacionamento?,Vendedor?,Comentario?,ModeloAparelho?,Contato?,OfertaInstancia?,CampanhaInstancia?,FaturamentoInstancia?,ClienteInstancia?,NumPortabilidade?,NovoMSISDN?,NovoIMEI?)>
<!ELEMENT AcaoInstancia (#PCDATA) >
<!ELEMENT DDD (#PCDATA) >
<!ELEMENT OiChip (#PCDATA) >
<!ELEMENT MSISDN (#PCDATA) >
<!ELEMENT IMEI (#PCDATA) >
<!ELEMENT OpcaoOiDados (#PCDATA) >
<!ELEMENT Relacionamento (#PCDATA) >
<!ELEMENT Vendedor (#PCDATA) >
<!ELEMENT Comentario (#PCDATA) >
<!ELEMENT ModeloAparelho (#PCDATA) >
<!ELEMENT Contato (#PCDATA) >
<!ELEMENT OfertaInstancia (#PCDATA) >
<!ELEMENT CampanhaInstancia (#PCDATA) >
<!ELEMENT FaturamentoInstancia (#PCDATA) >
<!ELEMENT ClienteInstancia (#PCDATA) >
<!ELEMENT NumPortabilidade (#PCDATA) >
<!ELEMENT NovoMSISDN (#PCDATA) >
<!ELEMENT NovoIMEI (#PCDATA) >
<!ELEMENT ListaConvergentes (Convergentes*) >
<!ELEMENT Convergentes (acaoConvergente?,tipo?,migraTecnologia?,numero?,velocidade?,velocidadeAtual?,tecnologia?,viabilidade?,nomePacote?,numPortabFixo?,operPortabFixo?,numSmartCard?,idFibra?,idEnderNetwin?,sistOrigem?)>
<!ELEMENT acaoConvergente (#PCDATA) >
<!ELEMENT tipo (#PCDATA) >
<!ELEMENT migraTecnologia (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT velocidade (#PCDATA) >
<!ELEMENT velocidadeAtual (#PCDATA) >
<!ELEMENT tecnologia (#PCDATA) >
<!ELEMENT viabilidade (#PCDATA) >
<!ELEMENT nomePacote (#PCDATA) >
<!ELEMENT numPortabFixo (#PCDATA) >
<!ELEMENT operPortabFixo (#PCDATA) >
<!ELEMENT numSmartCard (#PCDATA) >
<!ELEMENT idFibra (#PCDATA) >
<!ELEMENT idEnderNetwin (#PCDATA) >
<!ELEMENT sistOrigem (#PCDATA) >

=== mariobacellar/java-sample-4/xmlmanager/src/main/resources/data/input/dtd/ListaCriarOrdemServico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SiebelMessage SYSTEM "ListaCriarOrdemServico.dtd" >
<SiebelMessage IntObjectName="" MessageId="" MessageType="">
  <ListaCriarOrdemServico>
    <Dados OrigemRequisicao="">
      <ListaOrdens>
        <Ordem>
          <NumeroContaFatura>NumeroContaFatura</NumeroContaFatura>
          <NomePlano>NomePlano</NomePlano>
          <NomeCampanha>NomeCampanha</NomeCampanha>
          <NomeOferta>NomeOferta</NomeOferta>
          <PDV>PDV</PDV>
          <ListaInstancias>
            <Instancias>
              <AcaoInstancia>AcaoInstancia</AcaoInstancia>
              <DDD>DDD</DDD>
              <OiChip>OiChip</OiChip>
              <MSISDN>MSISDN</MSISDN>
              <IMEI>IMEI</IMEI>
              <OpcaoOiDados>OpcaoOiDados</OpcaoOiDados>
              <Relacionamento>Relacionamento</Relacionamento>
              <Vendedor>Vendedor</Vendedor>
              <Comentario>Comentario</Comentario>
              <ModeloAparelho>ModeloAparelho</ModeloAparelho>
              <Contato>Contato</Contato>
              <OfertaInstancia>OfertaInstancia</OfertaInstancia>
              <CampanhaInstancia>CampanhaInstancia</CampanhaInstancia>
              <FaturamentoInstancia>FaturamentoInstancia</FaturamentoInstancia>
              <ClienteInstancia>ClienteInstancia</ClienteInstancia>
              <NumPortabilidade>NumPortabilidade</NumPortabilidade>
              <NovoMSISDN>NovoMSISDN</NovoMSISDN>
              <NovoIMEI>NovoIMEI</NovoIMEI>
            </Instancias>
          </ListaInstancias>
          <ListaConvergentes>
            <Convergentes>
              <acaoConvergente>acaoConvergente</acaoConvergente>
              <tipo>tipo</tipo>
              <migraTecnologia>migraTecnologia</migraTecnologia>
              <numero>numero</numero>
              <velocidade>velocidade</velocidade>
              <velocidadeAtual>velocidadeAtual</velocidadeAtual>
              <tecnologia>tecnologia</tecnologia>
              <viabilidade>viabilidade</viabilidade>
              <nomePacote>nomePacote</nomePacote>
              <numPortabFixo>numPortabFixo</numPortabFixo>
              <operPortabFixo>operPortabFixo</operPortabFixo>
              <numSmartCard>numSmartCard</numSmartCard>
              <idFibra>idFibra</idFibra>
              <idEnderNetwin>idEnderNetwin</idEnderNetwin>
              <sistOrigem>sistOrigem</sistOrigem>
            </Convergentes>
          </ListaConvergentes>
        </Ordem>
      </ListaOrdens>
    </Dados>
  </ListaCriarOrdemServico>
</SiebelMessage>
